### ISSUE TITLE
please add the readme file with instruction - how to create build and use it in my angular/normal html app. 

### ISSUE THREAD

**Issue by vijaywavemaker** [rhuan-dev/website-preview-devices#19]
Hi @rhcarlosweb ,

Awesome work :)

please add the readme file with instruction for the below- 

- how to create build and use it in my angular/normal html app. 
- is it possible to just set the url of the website to your app and show!

Thank you so much for your help :)

**Comment by rhcarlosweb** [comment]
Hello @vijaywavemaker, so this pen i made in codepen is just to show a preview to my clients, showing how is gonna be applied in some devices

But i will do some readme file to explain how to change the images on code

**Comment by vijaywavemaker** [comment]
@rhcarlosweb thank you for your feedback.
I hope we can use iframe in place of div i guess. 👍 it will be great if u have single dist folder where it will have  .min version of js and css, html👍
